import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "AbuzOne Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className="bg-cover bg-center min-h-screen flex items-center justify-center "
        style={{
          backgroundImage: "url('/abuzone.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          minHeight: "100vh",
        }}
      >
        {children}
      </body>
    </html>
  );
}
